### ISSUE TITLE
Image upload and undo

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-upload#3] opened 2017-04-05 14:48 UTC
Image upload is a great opportunity to check how selective undo works. The user should be able to apply any changes during the upload, but the changes of the image status (update of the src attribute) should be part of the same batch and do not create additional undo steps.

It should be tests and bugs should be fixed.

Also, when user undoes image insertion, the image is removed and if the upload did not finish it should be stopped, like in https://github.com/ckeditor/ckeditor5-upload/issues/2.

**Comment by szymonkups** [comment] 2017-05-09 09:35
During the work on #2 I've found some scenarios regarding undo, which I think should be discussed.

## Scenario 1
1. Image is inserted into editor.
1. Upload starts.
1. An error occurs during upload - image is removed.

All those steps are using same `Batch` instance, so this creates an "empty" undo step in history (because it inserts and deletes the image). Should we leave it that way?

## Scenario 2
1. Image is inserted into editor.
1. Upload starts.
1. Image is removed using <kbd>Delete</kbd> key.

So now we have two `Batch` instances involved. One that inserts the image, second that was created in response to <kbd>Delete</kbd> key press. Should we also remove the image with batch used to insert it (to make it "empty" as in __Scenario 1__)? How the history will behave then?

## Scenario 3
1. Image is inserted into editor.
1. Upload starts.
1. Undo command is used.
This time we are undoing batch instead of removing the image directly. Should this be handled different than __Scenario 2__?

@scofalik @pjasiun @Reinmar

**Comment by Reinmar** [comment] 2017-05-09 13:43
The answer to all these questions is: this should work well from the user perspective. That's all. Only after we agree how it should work from the user perspective we can think how it should be implemented. The other way around focuses us on the wrong thing.

**Comment by Reinmar** [comment] 2017-05-09 13:47
My first question would be – can it happen now that inserting an image will break a paragraph? I couldn't reproduce it, but I guess this might happen one day. In such a case, in all scenarios, we may think how to take care of it. Of course, if it's doable and reasonable cause I'm not sure about this but nevertheless, it's something we need to think through.

**Comment by pjasiun** [comment] 2017-05-09 15:33
I think it should work the way you described it.

Note that between the image insertion and deletion might be some additional changes/batches, which should not be removed any way. Also, it means that we need to be sure that selective undo works fine. 

It is also possible that user removes part of the document (2 paragraphs of text with the image in between) what causes upload abort. In such case undo should cause reverting these paragraphs, but without the image.

It means that it might happen that on the undo stack we will have the image insert and image remove in separate batches. And I think it's fine. Selective undo should handle it. For instance, we might have:

Batch A: image insert
Batch B: remove image

If we will undo batch A, it will be transformed by batch B what means no image will be inserted. It also means that we may have an empty undo step even if there is no empty batch. What we can do with it, is to check it there are any changes, outside graveyard to be applied after the transformation. If no, it means that it's an empty undo step and one more undo should be applied.

However, I'm afraid that avoiding empty undo steps might be complicated and I would not handle it now.

**Comment by pjasiun** [comment] 2017-05-09 15:57
I think that there are 3 levels of the stability:
1. no bugs,
2. no empty undo steps,
3. nice UX.

For now, we should focus on step 1. Then we can think about empty undo steps.

As for nice UX: no empty steps might be enough. However, we can do more, for instance, could not canceling upload for a short while after the image is removed, letting user undo it and continue uploading. But these are hacks, and hacks usually lead to the very ugly code. Most probably the level 2 will be fine.

> The answer to all these questions is: this should work well from the user perspective.

I can't fully agree with it. This will be very tricky part of code, we should also think about how to implement it. Note that, since we will stop uploading when the image is removed, this is a change which can not be really undone. As a user, I would expect that the upload will continue from the moment it was when I removed the image. We will not be able to provide this (as far as I understand the technology). The solution will always be something "fine", not perfect, from the users perspective.

**Comment by pjasiun** [comment] 2017-05-09 15:59
> My first question would be – can it happen now that inserting an image will break a paragraph?

No. Image is always inserted before or after then block.

**Comment by Reinmar** [comment] 2017-05-09 18:27
Fair enough. And of course I totally agree with "no bugs" first, which I'd even change to "no crashes". No bugs means good UX (which is step 2. :D).

**Comment by Reinmar** [comment] 2017-05-09 18:28
> All those steps are using same Batch instance, so this creates an "empty" undo step in history (because it inserts and deletes the image). Should we leave it that way?

Can we mark it as transparent on the fly?

**Comment by pjasiun** [comment] 2017-05-10 07:42
> All those steps are using same Batch instance, so this creates an "empty" undo step in history (because it inserts and deletes the image). Should we leave it that way?
> Can we mark it as transparent on the fly?

The problem is that we will have an empty undo step even if there is no any "empty"/"transparent" batch. It's the result of the deltas transformations what is empty, not a single batch. There might be no good place to mark as transparent.

**Comment by scofalik** [comment] 2017-05-10 08:39
> The answer to all these questions is: this should work well from the user perspective.

I can't agree with it either. Honestly, we could do anything, given any amount of time. The thing is that we have to work within the rules that we created and try not to create hacky code. That's why we have to think how to implement solutions to described scenarios in a nice way.

Let me comment quickly on empty undo steps: for now, I believe, we are fine having them. We could implement some heuristics to detect whether given reverse-delta do anything and this should be neither difficult nor hacky. But for now this is the solution that we are going for.

> Can we mark it as transparent on the fly?

Well, we could, but this would require a change in undo feature - right now when batch is registered in undo (each non-transparent batch is when it's first operation is applied) then it is there. We would need to reverse this logic and check batches type on execution. But then command state would need to be updated whenever any batch type is updated. And, of course, this wasn't a case when implementing undo so I don't know if there are no other problems with this approach. But I think there are other ways to handle this situation (undo should be able to tell whether an undo step does anything), so let's really leave it for now.

Whether the upload should be aborted when user removes is up to us, but probably we would like to save bandwidth. Then, AFAIK, we can't trigger re-uploading, so aborting will not be undoable. We can of course later try to fix this issue by some UI elements letting user easier re-upload the image.

So, first of all, if we are aborting upload on image deletion, we need listener on `change` that will probe whether uploaded image was removed.

Scenario 1 is basic and easy. We will have an empty undo step for now. Let's remember that maybe this is not a very-rare case, but it is not common either.

Scenario 2 is more complicated but it is the same as scenario 3, actually.

What happens:
1. Image is inserted, creating _batch 1_ _operation insert_.
2. Upload starts.
3. User removes image, creating _batch 2_ _operation remove (from `posOriginal` to `posGy1`)_.
4. Upload is aborted, creating _batch 1_ _operation remove (from `posGy1` to `posGy2`)_.

Undo stack is:
Batch 1, operation insert.
Batch 2, operation remove.
Batch 1, operation remove.

When undo is executed, batches are undone in the reverse order of batch first-appearance. This means that batch 2 will be undone on the first undo step.

Now, when `RemoveOperation` is undone, it is reversed to `ReinsertOperation`. Then it will have to be transformed by all the operations beneath it on the stack, which is `RemoveOperation`. It should be something like this:

`ReinsertOperation` from `posGy1` to `posOriginal` x `RemoveOperation` from `posGy1` to `posGy2`.

In case when `RemoveOperation` is transformed by non-`RemoveOperation`, `RemoveOperation` is always considered "more important". So the result of this transformation should be `RemoveOperation` from `posGy2` to `posGy2` or `NoOperation` (probably a silly `RemoveOperation` though as I look at the code - we might make an improvement in this regard but AFAIR, for _reasons_ `RemoveOperation` should not become `NoOperation` ever).

This however is just theory and needs testing, I don't remember whether we had case like this or whether I ever tested it. Nevertheless, I have an opinion that, this is a correct chain of events and the result should be either and operation that does nothing or `NoOperation`.

Because undo is nothing more than just creating and applying an operation that reverses given operation. scenario 3 is the same as 2.

**Comment by Reinmar** [comment] 2017-07-07 08:21
## Scenario 1

Empty undo step. No crashes.

## Scenario 2

Two empty undo steps.

Also, a crash in this case, but I think it's nothing related to upload:

![jul-07-2017 10-16-09](https://user-images.githubusercontent.com/156149/27949290-71d530d0-62fd-11e7-84d2-9039c0175bb4.gif)

```
position.js:158 Uncaught TypeError: this.parent.offsetToIndex is not a function
    at Position.get index [as index] (position.js:158)
    at Position.get textNode [as textNode] (position.js:169)
    at Position.get nodeAfter [as nodeAfter] (position.js:181)
    at _fixItemsIndent (converters.js:629)
    at Document.<anonymous> (converters.js:576)
    at Document.fire (emittermixin.js:281)
    at Document.applyOperation (document.js:173)
    at UndoCommand._undo (basecommand.js:153)
    at Array.editor.document.enqueueChanges (undocommand.js:40)
    at Document.enqueueChanges (document.js:241)
```

I'll report it in https://github.com/ckeditor/ckeditor5-undo/issues/65.

## Scenario 3

Empty undo step.

## Mixed 

Typing + upload + typing + delete image works fine. Empty undo steps and empty paragraph appear, but that's not a big deal.

**Comment by Reinmar** [comment] 2017-07-07 08:27
I reported the empty undo steps issue in https://github.com/ckeditor/ckeditor5-undo/issues/66.

**Comment by Reinmar** [comment] 2017-07-07 08:29
I'd close this ticket as we fixed the crashes and reported followups elsewhere.

**Closed by Reinmar** 2017-07-07 08:29 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
